Controllers/EjerciciosFisicosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlanEjercicio.Data;
using PlanEjercicio.Models;

namespace PlanEjercicio.Controllers;
[Authorize]

public class EjerciciosFisicosController : Controller
{
    private ApplicationDbContext _context;

    public EjerciciosFisicosController(ApplicationDbContext context)
    {
        _context = context;
    }

    /* public IActionResult Index()
    {
        return View();
    } */

    //DropdownList
     public IActionResult Index()
    {
        // Crear una lista de SelectListItem que incluya el elemento adicional
        var selectListItems = new List<SelectListItem>
        {
            new SelectListItem { Value = "0", Text = "[SELECCIONE...]" }
        };

        // Obtener todas las opciones del enum
        var enumValues = Enum.GetValues(typeof(EstadoEmocional)).Cast<EstadoEmocional>();

        // Convertir las opciones del enum en SelectListItem
        selectListItems.AddRange(enumValues.Select(e => new SelectListItem
        {
            Value = e.GetHashCode().ToString(),
            Text = e.ToString().ToUpper()
        }));

        // Pasar la lista de opciones al modelo de la vista
        ViewBag.EstadoEmocionalInicio = selectListItems.OrderBy(t => t.Text).ToList();
        ViewBag.EstadoEmocionalFin = selectListItems.OrderBy(t => t.Text).ToList();

        var tipoEjercicios = _context.TipoEjercicios.ToList();
        tipoEjercicios.Add(new TipoEjercicio{IdEjercicio = 0, NombreEjercicio = "[SELECCIONE...]"});
        ViewBag.TipoEjercicioID = new SelectList(tipoEjercicios.OrderBy(c => c.NombreEjercicio), "IdEjercicio", "NombreEjercicio");

        return View();
    }

    

     public JsonResult ListadoEjerciciosFisicos(int? id)
    {

        
        List<VistaEjercicios> mostrarEjercicios = new List<VistaEjercicios>();
        
        var ejerciciosFisicos = _context.EjerciciosFisicos.ToList();

        
        if (id != null)
        {
            ejerciciosFisicos = ejerciciosFisicos.Where(e => e.EjercicioFisicoId == id).ToList();
        }

        var tiposEjercicios = _context.TipoEjercicios.ToList();

        foreach (var ejercicioFisicos in ejerciciosFisicos)
        {
            var tipoEjercicio = tiposEjercicios.Where(t => t.IdEjercicio == ejercicioFisicos.IdEjercicio).Single();

            var mostrarEjercicioFisico = new VistaEjercicios
            {
                EjercicioFisicoId = ejercicioFisicos.EjercicioFisicoId,
                IdEjercicio = ejercicioFisicos.IdEjercicio,
                TipoEjercicioNombre = tipoEjercicio.NombreEjercicio,
                InicioString = ejercicioFisicos.Inicio.ToString("dd/MM/yyyy HH:mm"),
                FinString = ejercicioFisicos.Fin.ToString("dd/MM/yyyy HH:mm"),
                EstadoEmocionalInicio = Enum.GetName(typeof(EstadoEmocional), ejercicioFisicos.EstadoEmocionalInicio),
                EstadoEmocionalFin = Enum.GetName(typeof(EstadoEmocional), ejercicioFisicos.EstadoEmocionalFin),
                Observaciones = ejercicioFisicos.Observaciones,

            };
            mostrarEjercicios.Add(mostrarEjercicioFisico);
        }

        return Json(mostrarEjercicios);
    }

    public JsonResult CargarEjercicios(int ejercicioFisicoId, int tipoEjercicioID, DateTime fechaInicio, DateTime fechaFin, EstadoEmocional estadoEmocionalInicio, EstadoEmocional estadoEmocionalFin, string? observaciones ) 
    {
        string resultado = "";
        if (ejercicioFisicoId == 0) 
        {
            var ejercicio = new EjercicioFisico
                {
                    EjercicioFisicoId = ejercicioFisicoId,
                    IdEjercicio = tipoEjercicioID,
                    Inicio = fechaInicio,
                    Fin = fechaFin,
                    EstadoEmocionalInicio = estadoEmocionalInicio,
                    EstadoEmocionalFin = estadoEmocionalFin,
                    Observaciones = observaciones,
                };
                _context.Add(ejercicio);
                _context.SaveChanges();
        }
        else 
        {
            var editarEjercicio = _context.EjerciciosFisicos.Where(t => t.EjercicioFisicoId == ejercicioFisicoId).SingleOrDefault();
            {
                var ejercicioExiste = _context.EjerciciosFisicos.Where(t => tipoEjercicioID == ejercicioFisicoId).Count();
                {
                    editarEjercicio.IdEjercicio = tipoEjercicioID;
                    editarEjercicio.Inicio = fechaInicio;
                    editarEjercicio.Fin = fechaFin;
                    editarEjercicio.EstadoEmocionalInicio = estadoEmocionalFin;
                    editarEjercicio.EstadoEmocionalFin = estadoEmocionalFin;
                    editarEjercicio.Observaciones = observaciones;

                }
            }
        }
            return Json (resultado);
    } 

public JsonResult ListadoEjercicios(int? id)
    {
        
        var ejerciciosFisicos = _context.EjerciciosFisicos.ToList();

        
        if (id != null)
        {
            ejerciciosFisicos = ejerciciosFisicos.Where(t => t.EjercicioFisicoId == id).ToList();
        }

        return Json(ejerciciosFisicos);
    }

    public JsonResult EliminarRegistroEjercicio (int ejercicioFisicoId) 
    {
         var ejercicio = _context.EjerciciosFisicos.Find(ejercicioFisicoId);
        _context.Remove(ejercicio);
        _context.SaveChanges();
        return Json(true);

}


}

Controllers/TipoEjerciciosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlanEjercicio.Data;
using PlanEjercicio.Models;
using SQLitePCL;


namespace PlanEjercicio.Controllers;
[Authorize]
public class TipoEjerciciosController : Controller
{
    private  ApplicationDbContext _context;
    //constructor
    public TipoEjerciciosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {

        return View();
    }

    //Metodo para mostrar la lista de los tipos de ejercicios
    public JsonResult ListadoEjercicios(int? id)
    {
        //se guarda en una variable el listado completo de los tipos de ejercicio
        var tipoEjercicios = _context.TipoEjercicios.ToList();

        //si el usuario ingresa un id pasa lo siguiente
        if (id != null)
        {
            tipoEjercicios = tipoEjercicios.Where(t => t.IdEjercicio == id).ToList();
        }

        return Json(tipoEjercicios);
    }

    //Metodo para nuevo ejercicio
    public JsonResult CargarNuevoEjercicio(int tipoEjercicioId, string descripcion)
    {
        string resultado = "";

        if (!String.IsNullOrEmpty(descripcion))
        {
            descripcion = descripcion.ToUpper();

            //Este if verifica si se esta creando o editando un nuevo registro

            if (tipoEjercicioId == 0)
            {
                //verifico si existe un registro en la base de datos
                var existeEjercicio = _context.TipoEjercicios.Where(t => t.NombreEjercicio == descripcion).Count();
                if (existeEjercicio == 0)
                {
                    //Guardo el ejercicio
                    var tipoEjercicio = new TipoEjercicio
                    {
                        NombreEjercicio = descripcion
                    };
                    _context.Add(tipoEjercicio);
                    _context.SaveChanges();
                }
                else
                {
                    resultado = "Ya esxite un registro con la misma descripcion";
                }
            }
            else
            {
                //Se va a editar el registro
                var editarTipoEjercicio = _context.TipoEjercicios.Where(t => t.IdEjercicio == tipoEjercicioId).SingleOrDefault();
                if (editarTipoEjercicio != null)
                {
                    //busco si existe un registro con el mismo nombre pero distinto id
                    var existeEjercicio = _context.TipoEjercicios.Where(t => t.NombreEjercicio == descripcion && t.IdEjercicio == tipoEjercicioId).Count();
                    if (existeEjercicio == 0)
                    {
                        editarTipoEjercicio.NombreEjercicio = descripcion;
                        _context.SaveChanges();
                    }
                    else
                    {
                        resultado = "YA existe un registro con la misma descripcion";
                    }
                }
            }
        }
        else
        {
            resultado = "Tiene que ingresar una descripcion";
        }
        return Json(resultado);
    }


    //Metodo para eliminar el ejercicio
    public JsonResult EliminarRegistro(int idEjercicio)
    {
        var tipoEjercicio = _context.TipoEjercicios.Find(idEjercicio);
        _context.Remove(tipoEjercicio);
        _context.SaveChanges();
        return Json(true);
    }

}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlanEjercicio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlanEjercicio.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />


</head>

<body>
    @if (SignInManager.IsSignedIn(User))
    {


        <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PlanEjercicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoEjercicios" asp-action="Index">Tipo Ejercicio</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EjerciciosFisicos" asp-action="Index">Ejercicios Fisicos</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container container-principal">
        <main role="main" class="pb-3 main-principal">
        
            @RenderBody()
        </main>
    </div>

    
    }
    else
    {
        <div class="container-fluid div-logout">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>